window.PROMPT_BASE =
  // 'Go through my chat history and come up with a long list of about 50-100 nuanced topics directly derived from our chat history that we could continue talking about, that represent all our previous discussions uniformly and fairly (including those arbitrarily far in the past: avoid recency bias), and absolutely do not make up topics that we have not discussed before. First output this list of topics and the context that led you to identify them. Then, cluster them into about 10 diverse, interesting, specific, and nuanced categories. For each category, come up with a couple of imaginative and exploratory suggested questions that are simple and short, that are based off of the list of prior discussion topics in that category, and directly and closely related to them, but are in some way more exploratory and imaginative and make for highly engaging conversation starters, in the space of the topics we have discussed. Optimize for my wanting to click on these suggested questions by making the questions intriguing, right up my alley, and worthy of exploration for me given our past conversations as I expect to learn something interesting, general, and useful from them. Output a 2-level JSON object with just a list of the category names, and for each one, output the long list of topics in that category, and separately, the couple of these question suggestions in that category.';
  // 'Go through my chat history and figure out some good topics for us to talk about today. Extract a long list of 50 to 100 topics that are directly based off of my search history. Cluster them into about 10 logical categories. For each category, come up with 3 suggested questions that are based off of the list of topics that have been discussed before under the category, but in some way more exploratory and imaginative. Output JSON with list of "category", and in each category, a list of "questions" in that category, and a list of "topics" in that category that we discussed before that contributed to these questions.';
  'Going over my chat history, come up with 50 extremely specific topics in the form of sentences or long several-word phrases that we have discussed in the past, categorize them into 10 diverse and interesting categories, and for each one, come up with 3 nuanced, imaginative, and exploratory questions based on all the topics in that category. list the categories as bullet points (without description-list format), and for each category, list just the 3 questions in that category, and for each question, list all the topics in the form of sentences or long several-word phrases that the question was based on. Output format:\n\n1. <Category 1>\n  * <Question 1>\n    - <Topic 1>\netc.';

window.PROMPT_PERSONALIZED =
  ' Refine the suggestions to be much more tied to the nuanced topics that have been explored in my chat history. Ensure these suggestions are significantly different and more specific compared to the original suggestions to reflect a higher level of personalization. Make sure the results are quite distinct from those provided under the standard personalized setting.';

window.PROMPT_FUTURE_TRENDS =
  ' Focus on speculative and emerging trends that look into the future of various fields. These suggestions should highlight visionary, forward-thinking ideas that extend beyond current developments. Ensure the results are significantly different from those focused on current trends.';

window.PROMPT_EXPLORATORY =
  ' Provide suggestions that delve deeper into creative and adventurous areas, pushing the boundaries of conventional ideas. These suggestions should encourage innovative thinking and exploration beyond the usual scope. Ensure the results are notably distinct from less exploratory suggestions.';
